<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SuperCricket.Content\SuperCricket.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SuperCricket.Simulation.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
